# Generated by Django 5.1.1 on 2024-12-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['region'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=255, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='back.region')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['departement'],
            },
        ),
        migrations.CreateModel(
            name='StructureSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_sanitaire', models.CharField(max_length=255)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='back.departement')),
            ],
            options={
                'verbose_name': 'Structure Sanitaire',
                'verbose_name_plural': 'Structures Sanitaires',
                'ordering': ['structure_sanitaire'],
            },
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=50)),
                ('age_group', models.CharField(choices=[('0-11 mois', '0-11 mois'), ('1-4 ans', '1-4 ans'), ('5-14 ans', '5-14 ans'), ('15-49 ans', '15-49 ans'), ('50+ ans', '50+ ans')], max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], default='M', max_length=10)),
                ('total_patients_tested', models.PositiveIntegerField(default=0)),
                ('total_malaria_positive', models.PositiveIntegerField(default=0)),
                ('total_tdr_tests', models.PositiveIntegerField(default=0)),
                ('positive_tdr_tests', models.PositiveIntegerField(default=0)),
                ('total_microscopy_tests', models.PositiveIntegerField(default=0)),
                ('positive_microscopy_tests', models.PositiveIntegerField(default=0)),
                ('pf_cases', models.PositiveIntegerField(default=0)),
                ('pm_cases', models.PositiveIntegerField(default=0)),
                ('po_cases', models.PositiveIntegerField(default=0)),
                ('pv_cases', models.PositiveIntegerField(default=0)),
                ('mixed_infections', models.PositiveIntegerField(default=0)),
                ('structure_sanitaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratoires', to='back.structuresanitaire')),
            ],
            options={
                'verbose_name': 'Laboratoire',
                'verbose_name_plural': 'Laboratoires',
                'ordering': ['mois', 'age_group'],
            },
        ),
        migrations.CreateModel(
            name='FemmeEnceinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], default='F', max_length=10)),
                ('total_cases_consulted', models.PositiveIntegerField(default=0)),
                ('suspected_malaria_cases', models.PositiveIntegerField(default=0)),
                ('untested_malaria_cases', models.PositiveIntegerField(default=0)),
                ('structure_sanitaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='femmes_enceintes', to='back.structuresanitaire')),
            ],
            options={
                'verbose_name': 'Femme Enceinte',
                'verbose_name_plural': 'Femmes Enceintes',
                'ordering': ['mois'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationPrenatale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], default='F', max_length=10)),
                ('total_femmes_cpn1', models.PositiveIntegerField(default=0)),
                ('tpi_1', models.PositiveIntegerField(default=0)),
                ('tpi_2', models.PositiveIntegerField(default=0)),
                ('tpi_3', models.PositiveIntegerField(default=0)),
                ('tpi_4', models.PositiveIntegerField(default=0)),
                ('tpi_5', models.PositiveIntegerField(default=0)),
                ('tpi_6', models.PositiveIntegerField(default=0)),
                ('structure_sanitaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_prenatales', to='back.structuresanitaire')),
            ],
            options={
                'verbose_name': 'Consultation Prénatale',
                'verbose_name_plural': 'Consultations Prénatales',
                'ordering': ['mois'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=50)),
                ('age_group', models.CharField(choices=[('0-11 mois', '0-11 mois'), ('1-4 ans', '1-4 ans'), ('5-14 ans', '5-14 ans'), ('15-49 ans', '15-49 ans'), ('50+ ans', '50+ ans')], max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], default='M', max_length=10)),
                ('total_cases_consulted', models.PositiveIntegerField(default=0)),
                ('suspected_malaria_cases', models.PositiveIntegerField(default=0)),
                ('untested_malaria_cases', models.PositiveIntegerField(default=0)),
                ('confirmed_malaria_cases', models.PositiveIntegerField(default=0)),
                ('structure_sanitaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='back.structuresanitaire')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['mois', 'age_group'],
            },
        ),
        migrations.CreateModel(
            name='TraitmentAntipaludique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=50)),
                ('age_group', models.CharField(choices=[('0-11 mois', '0-11 mois'), ('1-4 ans', '1-4 ans'), ('5-14 ans', '5-14 ans'), ('15-49 ans', '15-49 ans'), ('50+ ans', '50+ ans')], max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], default='M', max_length=10)),
                ('antipaludique_confirmed', models.PositiveIntegerField(default=0)),
                ('antipaludique_probable', models.PositiveIntegerField(default=0)),
                ('act_confirmed', models.PositiveIntegerField(default=0)),
                ('act_probable', models.PositiveIntegerField(default=0)),
                ('structure_sanitaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='back.structuresanitaire')),
            ],
            options={
                'verbose_name': 'Traitement Antipaludique',
                'verbose_name_plural': 'Traitements Antipaludiques',
                'ordering': ['mois', 'age_group'],
            },
        ),
    ]
